name: kafka-replicator-images
lang: unknown
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp-dockerfile
  docker_repos: ['unsynced-confluentinc/cp-enterprise-replicator', 'unsynced-confluentinc/cp-enterprise-replicator-executable']
  maven_phase: 'package'
  maven_skip_deploy: true
  use_packages: true
  cp_images: true
  os_types: ['ubi8']
  nano_version: true
  build_arm: true