name: kafka-replicator-images
lang: unknown
lang_version: unknown
codeowners:
  enable: true
git:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp-dockerfile
  execution_time_limit: {"hours": 4}
  docker_repos: ['confluentinc/cp-enterprise-replicator',
                 'confluentinc/cp-enterprise-replicator-executable']
  maven_phase: 'package'
  maven_skip_deploy: true
  os_types: ['ubi8']
  nano_version: true
  build_arm: true
  use_packages: true
  cp_images: true
  